# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - fowcp

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js version
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install frontend
      working-directory: frontend
      run: |
        npm i

    - name: Build  frontend
      working-directory: frontend
      run: |
        npm run build

    # Copy frontend build into backend folder
    - name: Copy frontend build to backend
      run: cp -r frontend/build backend/build


    # Build Backend
    - name: Install backend dependencies
      working-directory: backend
      run: npm i --omit=dev
      
    # Zip backend for deployment
    #- name: Archive backend for deployment
    #  working-directory: backend
    #  run: zip -r ../app.zip . 
     


    - name: Deploy to Azure Web App
      uses: Azure/static-web-apps-deploy@v1
      with:
        app-name: fowcp  
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}            
        action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
        app_location: "backend" # App source code path
       
        
        

