# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - fowcp

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js version
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install frontend
      working-directory: frontend
      run: |
        npm install

    - name: Build  frontend
      working-directory: frontend
      run: |
        npm run build

    # Copy frontend build into backend folder
    - name: Copy frontend build to backend
      run: cp -r frontend/build backend/frontend_build


    # Build Backend
    - name: Install backend dependencies
      working-directory: backend
      run: npm install --omit=dev
      
    # Zip backend for deployment
    - name: Archive backend for deployment
      run: |
        cd backend
        zip -r ../app.zip .
     
        
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_02B85078AAF048EE9A4D0A537513DE47 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_73CE24C1601946048015D03F5012C02A }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3D38BE77CDA843AF98495BA4CD3A4A52 }}


    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: fowcp               
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: app.zip    

